/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.table;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrianferialopez
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    DefaultTableModel model;
    
    public Table() {
        initComponents();
        prepararTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNueva = new javax.swing.JButton();
        btnNuevoElemento = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        labelFila = new javax.swing.JLabel();
        labelColumna = new javax.swing.JLabel();
        etiFila = new javax.swing.JTextField();
        etiCol = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        etiResultado = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        etiNuevoValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hola", null, null, null},
                {null, "Ma", null, null},
                {null, null, "Aio", null},
                {null, null, null, "Pa"}
            },
            new String [] {
                "Titulo 1", "Titulo 2", "Titulo 3", "Titulo 4"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        btnNueva.setText("Nueva");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnNuevoElemento.setText("Nuevo Elemento");
        btnNuevoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoElementoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Fila");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        labelFila.setText("Fila");

        labelColumna.setText("Columna");

        btnVer.setText("Ver Valor");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnIntroducir.setText("Introducir");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelFila)
                        .addGap(27, 27, 27)
                        .addComponent(labelColumna))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNueva)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiFila, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etiCol, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoElemento)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIntroducir)
                                    .addComponent(btnVer))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiResultado)
                                    .addComponent(etiNuevoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(btnNuevoElemento)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFila)
                    .addComponent(labelColumna))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer)
                    .addComponent(etiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntroducir)
                    .addComponent(etiNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        
        String filaVacia[] = new String[5];
        model.addRow(filaVacia);
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnNuevoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoElementoActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        
        String filaElemento[] = {"Adrián","Feria","661153928","25","Badalona"};
        model.addRow(filaElemento);
    }//GEN-LAST:event_btnNuevoElementoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filasel = jTable1.getSelectedRow();
        
        if(filasel == -1)
        {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
        }else{
            model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(filasel);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        
        int fila;
        int col;
        String valor;
        
        try{
            fila = Integer.parseInt(etiFila.getText());
            col = Integer.parseInt(etiCol.getText());
            
            model = (DefaultTableModel) jTable1.getModel();
            valor= (String) model.getValueAt(fila, col);
            etiResultado.setText(valor);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al recoger el valor.");
        }
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        
        int fila;
        int col;
        String nuevoValor;
        
        try{
            fila = Integer.parseInt(etiFila.getText());
            col = Integer.parseInt(etiCol.getText());
            nuevoValor = (String) etiNuevoValor.getText();
            
            model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(nuevoValor, fila, col);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al introducir datos.");
        }
    }//GEN-LAST:event_btnIntroducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnNuevoElemento;
    private javax.swing.JButton btnVer;
    private javax.swing.JTextField etiCol;
    private javax.swing.JTextField etiFila;
    private javax.swing.JTextField etiNuevoValor;
    private javax.swing.JTextField etiResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelColumna;
    private javax.swing.JLabel labelFila;
    // End of variables declaration//GEN-END:variables

    private void prepararTabla() {
        
        String titulos[] = {"Nombre","Apellidos","Teléfono","Edad","Ciudad"};
        
        model = new DefaultTableModel(null, titulos);
        
        jTable1.setModel(model);
    }
}
