/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.util.HashSet;
import java.util.Iterator;

/**
 *
 * @author adrianferialopez
 */
public class Grafica extends javax.swing.JFrame {

    private HashSet<Partido> hashPartidos;
    private ErroresGrafico error = new ErroresGrafico();
    
    public Grafica() {
        initComponents();
        hashPartidos = GestionFichero.leerFichero("partidos.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEqLocal = new javax.swing.JTextField();
        txtEqVisitante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGolesLocal = new javax.swing.JTextField();
        txtGolesVisit = new javax.swing.JTextField();
        btnVictoriaLocal = new javax.swing.JButton();
        btnIntro1 = new javax.swing.JButton();
        btnEmpat = new javax.swing.JButton();
        btnVictoriaVisit1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelPartidos = new javax.swing.JTextPane();
        btnTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Equipo Local");

        jLabel2.setText("Equipo Visitante");

        txtEqVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEqVisitanteActionPerformed(evt);
            }
        });

        jLabel3.setText("Goles");

        jLabel4.setText("Goles");

        btnVictoriaLocal.setText("Victoria Local");
        btnVictoriaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVictoriaLocalActionPerformed(evt);
            }
        });

        btnIntro1.setText("Introducir");
        btnIntro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntro1ActionPerformed(evt);
            }
        });

        btnEmpat.setText("Empate");
        btnEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpatActionPerformed(evt);
            }
        });

        btnVictoriaVisit1.setText("Victoria Visitant");
        btnVictoriaVisit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVictoriaVisit1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(panelPartidos);

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEqVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGolesVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEqLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGolesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnIntro1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVictoriaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVictoriaVisit1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEqLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtGolesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEqVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtGolesVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIntro1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVictoriaLocal)
                    .addComponent(btnEmpat)
                    .addComponent(btnVictoriaVisit1)
                    .addComponent(btnTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEqVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEqVisitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEqVisitanteActionPerformed

    private void btnIntro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntro1ActionPerformed
            String nomLocal = txtEqLocal.getText();
            String nomVisit = txtEqVisitante.getText();
        try{
            int gLocal = Integer.parseInt(txtGolesLocal.getText());
            int gVisit = Integer.parseInt(txtGolesVisit.getText());
            Partido p = new Partido(nomLocal, nomVisit, gLocal, gVisit);
            hashPartidos.add(p);
        }catch(ExceptionNoInteger e){
            error.mostrarError("ERROR AL INTRODUCIR LOS GOLES...Han de ser valores enteros.");
        }
        
    }//GEN-LAST:event_btnIntro1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        GestionFichero.escribirArchivo("partidos.txt", hashPartidos);
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVictoriaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVictoriaLocalActionPerformed
        String local = "";
        
        Iterator<Partido> it = hashPartidos.iterator();
        Partido p;
        while(it.hasNext()){
            p = it.next();
            if(p.resultado() == 1) //gana el equipo local.
            {
                local = local + p.toString()+"\n";
            }
        }
        panelPartidos.setText(local);
    }//GEN-LAST:event_btnVictoriaLocalActionPerformed

    private void btnVictoriaVisit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVictoriaVisit1ActionPerformed
        String visitant = "";
        
        Iterator<Partido> it = hashPartidos.iterator();
        Partido p;
        while(it.hasNext()){
            p=it.next();
            if(p.resultado()==-1)//gana equipo visitante
            {
                visitant = visitant + p.toString()+"\n";
            }
        }
        panelPartidos.setText(visitant);
    }//GEN-LAST:event_btnVictoriaVisit1ActionPerformed

    private void btnEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpatActionPerformed
        String empate = "";
        
        Iterator<Partido> it = hashPartidos.iterator();
        Partido p;
        while(it.hasNext()){
            p=it.next();
            if(p.resultado() == 0) //empate
            {
                empate = empate + p.toString()+"\n";
            }
        }
        panelPartidos.setText(empate);
    }//GEN-LAST:event_btnEmpatActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        String todos = "";
        
        Iterator<Partido> it = hashPartidos.iterator();
        Partido p;
        while(it.hasNext()){
            p=it.next();
            todos=todos+p.toString()+"\n";
        }
        panelPartidos.setText(todos);
    }//GEN-LAST:event_btnTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpat;
    private javax.swing.JButton btnIntro1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTodos;
    private javax.swing.JButton btnVictoriaLocal;
    private javax.swing.JButton btnVictoriaVisit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane panelPartidos;
    private javax.swing.JTextField txtEqLocal;
    private javax.swing.JTextField txtEqVisitante;
    private javax.swing.JTextField txtGolesLocal;
    private javax.swing.JTextField txtGolesVisit;
    // End of variables declaration//GEN-END:variables
}
