/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.loteria;

import java.util.ArrayList;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author adrianferialopez
 */
public class Interfaz_loteria extends javax.swing.JFrame {

    private ArrayList<Aposta> arrayApostes;
    private AplicacioApostes gApostes; 
    
    /**
     * Creates new form Interfaz_loteria
     */
    public Interfaz_loteria() {
        initComponents();
        arrayApostes = GestioArxiu.leerFichero("apostes.txt");
        gApostes = new AplicacioApostes(arrayApostes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarApostes = new javax.swing.JButton();
        btnMostrarAposta = new javax.swing.JButton();
        btnAfegirAposta = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        Sortir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextPane();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApuesta = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrarApostes.setText("Mostrar Apostes");
        btnMostrarApostes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarApostesActionPerformed(evt);
            }
        });

        btnMostrarAposta.setText("Mostrar Aposta");
        btnMostrarAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarApostaActionPerformed(evt);
            }
        });

        btnAfegirAposta.setText("Afegir Aposta");
        btnAfegirAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirApostaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Aposta");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Aposta");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        Sortir.setText("Sortir");
        Sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortirActionPerformed(evt);
            }
        });

        txtPanel.setEditable(false);
        jScrollPane1.setViewportView(txtPanel);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apuesta");

        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAfegirAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarApostes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sortir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarApostes)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarAposta)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegirAposta)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar)
                            .addComponent(txtApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(Sortir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultar(){
        txtNombre.setEditable(false);
        txtApuesta.setEditable(false);
    }
    
    
    private void btnMostrarApostesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarApostesActionPerformed
       
        ocultar();
        
        try {
            txtPanel.setText(gApostes.mostrarApostes());
        } catch (ExepcioArrayBuit ex) {
            txtPanel.setText("No hi ha cap aposta");
        }
        
    }//GEN-LAST:event_btnMostrarApostesActionPerformed

    private void btnMostrarApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarApostaActionPerformed
        btnAccion.setText("Mostrar");
        txtNombre.setEditable(true);
        txtApuesta.setEditable(false);
        
    }//GEN-LAST:event_btnMostrarApostaActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed

        String nom;
        Double aposta;
        
        switch(btnAccion.getText())
        {
            case "Mostrar":
                nom = txtNombre.getText();
           {
                try {
                    txtPanel.setText(gApostes.mostrarAposta(nom));
                }catch (ExepcioArrayBuit ex) {
                    txtPanel.setText("No hi ha apostes");
                }catch (ExepcioApostaInexistent ex) {
                    txtPanel.setText("Aposta inexistent.");
                }
            }
                break;
            case "Afegir":
            {
                nom = txtNombre.getText();
                aposta = Double.parseDouble(txtApuesta.getText());
                try {
                    txtPanel.setText(gApostes.afegirAposta(nom, aposta));
                } catch (ExepcioApostaExistent ex) {
                    txtPanel.setText("Aposta existent");
                    }
            }
                break;
            case "Eliminar":
                nom = txtNombre.getText();
            {
                try {
                    txtPanel.setText(gApostes.eliminarAposta(nom));
                } catch (ExepcioArrayBuit ex) {
                    txtPanel.setText("No hi ha apostes");
                } catch (ExepcioApostaInexistent ex) {
                    txtPanel.setText("Aposta inexistent");
                }
            }  
                break;
            case "Modificar":
                nom = txtNombre.getText();
                aposta = Double.parseDouble(txtApuesta.getText());
        {
            try {
                txtPanel.setText(gApostes.modificarAposta(nom, aposta));
            } catch (ExepcioArrayBuit ex) {
                Logger.getLogger(Interfaz_loteria.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExepcioApostaInexistent ex) {
                Logger.getLogger(Interfaz_loteria.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExepcioApostaExistent ex) {
                Logger.getLogger(Interfaz_loteria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnAfegirApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirApostaActionPerformed
        btnAccion.setText("Afegir");
        txtNombre.setEditable(true);
        txtApuesta.setEditable(true);
    }//GEN-LAST:event_btnAfegirApostaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        btnAccion.setText("Eliminar");
        txtApuesta.setEditable(false);
        txtNombre.setEditable(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnAccion.setText("Modificar");
        txtNombre.setEditable(true);
        txtApuesta.setEditable(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void SortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortirActionPerformed
        GestioArxiu.escribirArxiu("apostes.txt", arrayApostes);
        System.exit(0);
    }//GEN-LAST:event_SortirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_loteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sortir;
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnAfegirAposta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarAposta;
    private javax.swing.JButton btnMostrarApostes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApuesta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextPane txtPanel;
    // End of variables declaration//GEN-END:variables
}
